name: Java Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build project with Maven
      run: |
        cd nitconf/nitconf
        mvn -B package --file pom.xml
