name: Java Maven CI/CD with Test Coverage

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Build project with Maven
      run: |
        cd nitconf/nitconf
        mvn -B package --file pom.xml
